baseURL = "http://jorgesolajais.com.ar/"
languageCode = "es"
title = "Jorge Solá Jais"
theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"